Fix the build on macOS
There are apparently some "Linux-isms" in the codebase which
prevented things from building on macOS.

`-Werror` enables "warn-as-error", which means the *many* warnings
produced by the build become errors:

	clang: error: -Wl,-z,relro: 'linker' input unused [-Werror,-Wunused-command-line-argument]
	clang: error: -Wl,-z,now: 'linker' input unused [-Werror,-Wunused-command-line-argument]
	clang: error: -Wl,-z,noexecstack: 'linker' input unused [-Werror,-Wunused-command-line-argument]
	clang: error: -Wl,-z,separate-code: 'linker' input unused [-Werror,-Wunused-command-line-argument]

Disable `-Werror`.

Similarly, clang doesn't support `-z`, meaning once we allow warnings
to exist, the above e.g. `-Wl,-z,relro` results in a link-time error:

	ld: unknown option: -z
	clang: error: linker command failed with exit code 1 (use -v to see invocation)

Disable `-Wl,-z,…`.

Finally, for reasons I can't fathom, **snprintf**(3) couldn't be found:

	log.c:156:2: error: implicitly declaring library function 'snprintf' with type 'int (char *, unsigned long, const char *, ...)' [-Werror,-Wimplicit-function-declaration]
	        snprintf(logfile, (size_t)MAX_PATH_LEN, "%s/%s", conf_log_root,
	        ^

Explicitly set `_C99_SOURCE=1` so that the definition can be found.

This allows `bip` to build and link (with many *many* warnings).